# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:

  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - virtual_roll_joint
      - virtual_yaw_joint
      
  gripper_controller:
    type: GripperCommand
    joints:
      - gripper
    action_ns: gripper_cmd
    default: true